import { ApplicationConfig, isDevMode, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideServiceWorker } from '@angular/service-worker';
import { provideRouter } from '@angular/router';
import { provideIonicAngular } from '@ionic/angular';
import { addIcons } from 'ionicons';
import {
  home,
  settings,
  add,
  statsChart,
  search,
  disc,
  grid,
  ellipsisVertical,
  logoGoogle,
  car,
  wallet,
  book,
  calendar,
  lockClosed,
  heart,
  chevronForward,
  chevronBack,
  build,
  camera,
  carSportOutline,
  cameraOutline,
  pricetagOutline,
  calendarOutline,
  chevronDownOutline,
  cardOutline,
  batteryChargingOutline,
  waterOutline,
  speedometerOutline,
  informationCircleOutline,
  cloudy,
  location,
  flash,
  cash,
  checkmark,
  documentText,
  carSport,
  scanOutline,
  restaurantOutline,
  people,
  personAdd,
  copy,
  refresh,
  bulbOutline,
  notifications,
  sunny,
  layersOutline,
  sparklesOutline,
  optionsOutline,
  shuffle,
  trashOutline,
  restaurant,
  cart,
  moon,
  timer,
  phonePortrait,
  shieldCheckmark,
} from 'ionicons/icons';
import { routes } from './app.routes';

addIcons({
  home,
  settings,
  add,
  statsChart,
  search,
  disc,
  grid,
  ellipsisVertical,
  logoGoogle,
  car,
  wallet,
  book,
  calendar,
  lockClosed,
  heart,
  chevronForward,
  chevronBack,
  build,
  camera,
  carSportOutline,
  cameraOutline,
  pricetagOutline,
  calendarOutline,
  chevronDownOutline,
  cardOutline,
  batteryChargingOutline,
  waterOutline,
  speedometerOutline,
  informationCircleOutline,
  cloudy,
  location,
  flash,
  cash,
  checkmark,
  documentText,
  carSport,
  scanOutline,
  restaurantOutline,
  people,
  personAdd,
  copy,
  refresh,
  bulbOutline,
  notifications,
  sunny,
  layersOutline,
  sparklesOutline,
  optionsOutline,
  shuffle,
  trashOutline,
  restaurant,
  cart,
  moon,
  timer,
  phonePortrait,
  shieldCheckmark,
});

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideServiceWorker('ngsw-worker.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:30000',
    }),
    provideIonicAngular({ swipeBackEnabled: true }),
  ],
};
