import { inject, Injectable } from '@angular/core';
import { FirestoreDocument, FirestoreService, FirestoreValue } from '../../../core/firebase/firestore.service';
import { AuthService } from '../authentication/authentication.service';
import { FamilyContext, FamilyMember, FamilyRecord } from './family.model';
const text=(v:string):FirestoreValue=>({stringValue:v}); const bool=(v:boolean):FirestoreValue=>({booleanValue:v}); const texts=(v:string[]):FirestoreValue=>({arrayValue:{values:v.map(text)}});

@Injectable({providedIn:'root'}) export class FamilyService {
  private readonly auth=inject(AuthService); private readonly db=inject(FirestoreService);
  async context():Promise<FamilyContext|null>{const {uid,token}=await this.auth.getSession();const profile=await this.db.tryGetDocument(`users/${uid}`,token);const familyId=profile?.fields?.['familyId']?.stringValue??'';const ownerId=profile?.fields?.['familyOwnerId']?.stringValue??'';return familyId&&ownerId?{familyId,ownerId}:null;}
  async load():Promise<{family:FamilyRecord;members:FamilyMember[]}|null>{const {token}=await this.auth.getSession();const context=await this.context();if(!context)return null;const doc=await this.db.tryGetDocument(`families/${context.familyId}`,token);if(!doc)return null;const members=(await this.db.listDocuments(`families/${context.familyId}/members`,token)).map(d=>this.member(d));return{family:this.family(doc),members};}
  async create(name:string):Promise<void>{const {uid,token}=await this.auth.getSession();const profile=await this.db.getDocument(`users/${uid}`,token);const id=crypto.randomUUID();const fields={name:text(name.trim()||'My Family'),ownerId:text(uid),memberIds:texts([uid]),sharePlanning:bool(true),shareRecipes:bool(true),createdAt:{timestampValue:new Date().toISOString()}};await this.db.createDocument('families',id,fields,token);await this.db.createDocument(`families/${id}/members`,uid,this.memberFields(profile,'Owner'),token);await this.db.updateDocument(`users/${uid}`,{familyId:text(id),familyOwnerId:text(uid)},token);}
  async invite(email:string):Promise<string>{const {uid,token}=await this.auth.getSession();const context=await this.context();if(!context)throw new Error('Create a family first.');const code=crypto.randomUUID();await this.db.createDocument('familyInvites',code,{familyId:text(context.familyId),ownerId:text(context.ownerId),email:text(email.trim().toLowerCase()),active:bool(true),createdBy:text(uid),createdAt:{timestampValue:new Date().toISOString()}},token);return code;}
  async join(code:string):Promise<void>{const {uid,token}=await this.auth.getSession();const invite=await this.db.getDocument(`familyInvites/${encodeURIComponent(code.trim())}`,token);if(!(invite.fields?.['active']?.booleanValue??false))throw new Error('This invitation is no longer active.');const familyId=invite.fields?.['familyId']?.stringValue??'';const ownerId=invite.fields?.['ownerId']?.stringValue??'';const familyDoc=await this.db.getDocument(`families/${familyId}`,token);const family=this.family(familyDoc);if(!family.memberIds.includes(uid))family.memberIds.push(uid);await this.db.updateDocument(`families/${familyId}`,{memberIds:texts(family.memberIds),lastInviteCode:text(code.trim())},token);const profile=await this.db.getDocument(`users/${uid}`,token);await this.db.createDocument(`families/${familyId}/members`,uid,this.memberFields(profile,'Member'),token).catch(async()=>this.db.updateDocument(`families/${familyId}/members/${uid}`,this.memberFields(profile,'Member'),token));await this.db.updateDocument(`users/${uid}`,{familyId:text(familyId),familyOwnerId:text(ownerId)},token);}
  async updateSharing(family:FamilyRecord,field:'sharePlanning'|'shareRecipes',value:boolean):Promise<void>{const {token}=await this.auth.getSession();await this.db.updateDocument(`families/${family.id}`,{[field]:bool(value)},token);}
  async leave(family:FamilyRecord):Promise<void>{const {uid,token}=await this.auth.getSession();if(uid===family.ownerId)throw new Error('The owner cannot leave the family.');await this.db.updateDocument(`families/${family.id}`,{memberIds:texts(family.memberIds.filter(x=>x!==uid))},token);await this.db.deleteDocument(`families/${family.id}/members`,uid,token);await this.db.updateDocument(`users/${uid}`,{familyId:text(''),familyOwnerId:text('')},token);}
  private family(d:FirestoreDocument):FamilyRecord{const f=d.fields??{};return{id:d.name.split('/').at(-1)??'',name:f['name']?.stringValue??'Family',ownerId:f['ownerId']?.stringValue??'',memberIds:f['memberIds']?.arrayValue?.values?.map(x=>x.stringValue??'').filter(Boolean)??[],sharePlanning:f['sharePlanning']?.booleanValue??true,shareRecipes:f['shareRecipes']?.booleanValue??true,createdAt:f['createdAt']?.timestampValue??''};}
  private member(d:FirestoreDocument):FamilyMember{const f=d.fields??{};return{id:d.name.split('/').at(-1)??'',displayName:f['displayName']?.stringValue??'Family member',email:f['email']?.stringValue??'',photoUrl:f['photoUrl']?.stringValue??'',role:(f['role']?.stringValue??'Member') as FamilyMember['role']};}
  private memberFields(profile:FirestoreDocument,role:FamilyMember['role']){const f=profile.fields??{};return{displayName:text(f['displayName']?.stringValue??'Family member'),email:text(f['email']?.stringValue??''),photoUrl:text(f['photoUrl']?.stringValue??''),role:text(role)};}
}
