import { inject, Injectable } from '@angular/core';
import { FirestoreDocument, FirestoreService, FirestoreValue } from '../../../core/firebase/firestore.service';
import { AuthService } from '../authentication/authentication.service';
import { FamilyContext, FamilyInvite, FamilyMember, FamilyRecord } from './family.model';
const text=(v:string):FirestoreValue=>({stringValue:v}); const bool=(v:boolean):FirestoreValue=>({booleanValue:v}); const texts=(v:string[]):FirestoreValue=>({arrayValue:{values:v.map(text)}});

@Injectable({providedIn:'root'}) export class FamilyService {
  private readonly auth=inject(AuthService); private readonly db=inject(FirestoreService);
  async removeMember(family: FamilyRecord, memberId: string): Promise<void> {
    const { uid, token } = await this.auth.getSession();
    if (uid !== family.ownerId) throw new Error('Only the family owner can remove members.');
    if (memberId === family.ownerId) throw new Error('The family owner cannot be removed.');
    if (!family.memberIds.includes(memberId)) throw new Error('This person is no longer in the family.');
    await this.db.commitWrites([
      { transform: { document: this.db.documentName(`families/${family.id}`), fieldTransforms: [
        { fieldPath: 'memberIds', removeAllFromArray: { values: [text(memberId)] } }
      ] } },
      { delete: this.db.documentName(`families/${family.id}/members/${memberId}`) },
      { update: { name: this.db.documentName(`users/${memberId}`), fields: { familyId: text(''), familyOwnerId: text('') } },
        updateMask: { fieldPaths: ['familyId', 'familyOwnerId'] }, currentDocument: { exists: true } }
    ], token);
  }
  async context():Promise<FamilyContext|null>{const {uid,token}=await this.auth.getSession();const profile=await this.db.tryGetDocument(`users/${uid}`,token);const familyId=profile?.fields?.['familyId']?.stringValue??'';const ownerId=profile?.fields?.['familyOwnerId']?.stringValue??'';return familyId&&ownerId?{familyId,ownerId}:null;}
  async load():Promise<{family:FamilyRecord;members:FamilyMember[]}|null>{const {token}=await this.auth.getSession();const context=await this.context();if(!context)return null;const doc=await this.db.tryGetDocument(`families/${context.familyId}`,token);if(!doc)return null;const members=(await this.db.listDocuments(`families/${context.familyId}/members`,token)).map(d=>this.member(d));return{family:this.family(doc),members};}
  async pendingInvites():Promise<FamilyInvite[]>{const {uid,token}=await this.auth.getSession();const profile=await this.db.getDocument(`users/${uid}`,token);const email=(profile.fields?.['email']?.stringValue??'').trim().toLowerCase();if(!email)return[];return(await this.db.queryDocuments('familyInvites','email',text(email),token)).map(d=>this.inviteRecord(d)).filter(x=>x.active);}
  async create(name:string):Promise<void>{const {uid,token}=await this.auth.getSession();const profile=await this.db.getDocument(`users/${uid}`,token);const id=crypto.randomUUID();const fields={name:text(name.trim()||'My Family'),ownerId:text(uid),memberIds:texts([uid]),sharePlanning:bool(true),shareRecipes:bool(true),createdAt:{timestampValue:new Date().toISOString()}};await this.db.createDocument('families',id,fields,token);await this.db.createDocument(`families/${id}/members`,uid,this.memberFields(profile,'Owner'),token);await this.db.updateDocument(`users/${uid}`,{familyId:text(id),familyOwnerId:text(uid)},token);}
  async invite(email:string):Promise<string>{const {uid,token}=await this.auth.getSession();const context=await this.context();if(!context)throw new Error('Create a family first.');const normalized=email.trim().toLowerCase();if(!normalized)throw new Error('Enter the member\'s Google sign-in email.');const family=await this.db.getDocument(`families/${context.familyId}`,token);const code=crypto.randomUUID();await this.db.createDocument('familyInvites',code,{familyId:text(context.familyId),familyName:text(family.fields?.['name']?.stringValue??'Family'),ownerId:text(context.ownerId),email:text(normalized),active:bool(true),createdBy:text(uid),createdAt:{timestampValue:new Date().toISOString()}},token);return code;}
  async join(code:string):Promise<void>{const {uid,token}=await this.auth.getSession();const inviteCode=code.trim();if(!inviteCode)throw new Error('Enter an invitation code.');const invite=await this.db.getDocument(`familyInvites/${encodeURIComponent(inviteCode)}`,token);if(!(invite.fields?.['active']?.booleanValue??false))throw new Error('This invitation is no longer active.');const familyId=invite.fields?.['familyId']?.stringValue??'';const ownerId=invite.fields?.['ownerId']?.stringValue??'';if(!familyId||!ownerId)throw new Error('This invitation is invalid.');await this.db.commitWrites([{update:{name:this.db.documentName(`families/${familyId}`),fields:{lastInviteCode:text(inviteCode)}},updateMask:{fieldPaths:['lastInviteCode']},updateTransforms:[{fieldPath:'memberIds',appendMissingElements:{values:[text(uid)]}}]}],token);const profile=await this.db.getDocument(`users/${uid}`,token);await this.db.createDocument(`families/${familyId}/members`,uid,this.memberFields(profile,'Member'),token).catch(async()=>this.db.updateDocument(`families/${familyId}/members/${uid}`,this.memberFields(profile,'Member'),token));await this.db.updateDocument(`users/${uid}`,{familyId:text(familyId),familyOwnerId:text(ownerId)},token);await this.db.updateDocument(`familyInvites/${encodeURIComponent(inviteCode)}`,{active:bool(false)},token);}
  async updateSharing(family:FamilyRecord,field:'sharePlanning'|'shareRecipes',value:boolean):Promise<void>{const {token}=await this.auth.getSession();await this.db.updateDocument(`families/${family.id}`,{[field]:bool(value)},token);}
  async leave(family:FamilyRecord):Promise<void>{const {uid,token}=await this.auth.getSession();if(uid===family.ownerId)throw new Error('The owner cannot leave the family.');await this.db.updateDocument(`families/${family.id}`,{memberIds:texts(family.memberIds.filter(x=>x!==uid))},token);await this.db.deleteDocument(`families/${family.id}/members`,uid,token);await this.db.updateDocument(`users/${uid}`,{familyId:text(''),familyOwnerId:text('')},token);}
  private family(d:FirestoreDocument):FamilyRecord{const f=d.fields??{};return{id:d.name.split('/').at(-1)??'',name:f['name']?.stringValue??'Family',ownerId:f['ownerId']?.stringValue??'',memberIds:f['memberIds']?.arrayValue?.values?.map(x=>x.stringValue??'').filter(Boolean)??[],sharePlanning:f['sharePlanning']?.booleanValue??true,shareRecipes:f['shareRecipes']?.booleanValue??true,createdAt:f['createdAt']?.timestampValue??''};}
  private member(d:FirestoreDocument):FamilyMember{const f=d.fields??{};return{id:d.name.split('/').at(-1)??'',displayName:f['displayName']?.stringValue??'Family member',email:f['email']?.stringValue??'',photoUrl:f['photoUrl']?.stringValue??'',role:(f['role']?.stringValue??'Member') as FamilyMember['role']};}
  private inviteRecord(d:FirestoreDocument):FamilyInvite{const f=d.fields??{};return{id:d.name.split('/').at(-1)??'',familyId:f['familyId']?.stringValue??'',ownerId:f['ownerId']?.stringValue??'',familyName:f['familyName']?.stringValue??'Family',email:f['email']?.stringValue??'',active:f['active']?.booleanValue??false,createdAt:f['createdAt']?.timestampValue??''};}
  private memberFields(profile:FirestoreDocument,role:FamilyMember['role']){const f=profile.fields??{};return{displayName:text(f['displayName']?.stringValue??'Family member'),email:text(f['email']?.stringValue??''),photoUrl:text(f['photoUrl']?.stringValue??''),role:text(role)};}
}
